import {
  LucideAperture,
  LucideArmchair,
  LucideBaby,
  LucideBanknote,
  LucideBath,
  LucideBed,
  LucideBedDouble,
  LucideBell,
  LucideBike,
  LucideBookmark,
  LucideBox,
  LucideBoxes,
  LucideCar,
  LucideCoffee,
  LucideComputer,
  LucideDumbbell,
  LucideFlower2,
  LucideGamepad2,
  LucideGlassWater,
  LucideHammer,
  LucideHardDrive,
  LucideHeadphones,
  LucideHeart,
  LucideHome,
  LucideHotel,
  LucideIceCream,
  LucideKey,
  LucideLaptop,
  LucideLaugh,
  LucideLibrary,
  LucideLightbulb,
  LucideLink,
  LucideList,
  LucideMapPin,
  LucideMic,
  LucideMonitor,
  LucideMountain,
  LucideMusic,
  LucidePaperclip,
  LucideParkingCircle,
  LucidePenTool,
  LucidePhone,
  LucidePiggyBank,
  LucidePlane,
  LucidePlay,
  LucidePlug,
  LucidePrinter,
  LucideReceipt,
  LucideRefrigerator,
  LucideRocket,
  LucideRows,
  LucideSave,
  LucideSchool,
  LucideScissors,
  LucideServer,
  LucideShield,
  LucideShirt,
  LucideShoppingBag,
  LucideSignal,
  LucideSmile,
  LucideSofa,
  LucideSparkles,
  LucideSpeaker,
  LucideStar,
  LucideSun,
  LucideSunrise,
  LucideSunset,
  LucideTable,
  LucideTarget,
  LucideThermometer,
  LucideTimer,
  LucideTrain,
  LucideTreeDeciduous,
  LucideTrophy,
  LucideTv,
  LucideUmbrella,
  LucideUser,
  LucideUsers,
  LucideUtensilsCrossed,
  LucideVideo,
  LucideVolume2,
  LucideWallet,
  LucideWatch,
  LucideWifi,
  LucideWind,
  LucideWrench,
  LucideZap,
} from "lucide-react";

export const ICON_MAP = {
  aperture: LucideAperture,
  armchair: LucideArmchair,
  baby: LucideBaby,
  banknote: LucideBanknote,
  bath: LucideBath,
  bed: LucideBed,
  "bed-double": LucideBedDouble,
  bell: LucideBell,
  bike: LucideBike,
  book: LucideBookmark,
  bookmark: LucideBookmark,
  box: LucideBox,
  boxes: LucideBoxes,
  car: LucideCar,
  coffee: LucideCoffee,
  computer: LucideComputer,
  dumbbell: LucideDumbbell,
  "flower-2": LucideFlower2,
  "gamepad-2": LucideGamepad2,
  "glass-water": LucideGlassWater,
  hammer: LucideHammer,
  "hard-drive": LucideHardDrive,
  headphones: LucideHeadphones,
  heart: LucideHeart,
  home: LucideHome,
  hotel: LucideHotel,
  "ice-cream": LucideIceCream,
  key: LucideKey,
  laptop: LucideLaptop,
  laugh: LucideLaugh,
  library: LucideLibrary,
  lightbulb: LucideLightbulb,
  link: LucideLink,
  list: LucideList,
  "map-pin": LucideMapPin,
  mic: LucideMic,
  monitor: LucideMonitor,
  mountain: LucideMountain,
  music: LucideMusic,
  paperclip: LucidePaperclip,
  "parking-circle": LucideParkingCircle,
  "pen-tool": LucidePenTool,
  phone: LucidePhone,
  piggybank: LucidePiggyBank,
  plane: LucidePlane,
  play: LucidePlay,
  plug: LucidePlug,
  printer: LucidePrinter,
  receipt: LucideReceipt,
  refrigerator: LucideRefrigerator,
  rocket: LucideRocket,
  rows: LucideRows,
  save: LucideSave,
  school: LucideSchool,
  scissors: LucideScissors,
  server: LucideServer,
  shield: LucideShield,
  shirt: LucideShirt,
  "shopping-bag": LucideShoppingBag,
  signal: LucideSignal,
  smile: LucideSmile,
  sofa: LucideSofa,
  sparkles: LucideSparkles,
  speaker: LucideSpeaker,
  star: LucideStar,
  sun: LucideSun,
  sunrise: LucideSunrise,
  sunset: LucideSunset,
  table: LucideTable,
  target: LucideTarget,
  thermometer: LucideThermometer,
  timer: LucideTimer,
  train: LucideTrain,
  "tree-deciduous": LucideTreeDeciduous,
  trophy: LucideTrophy,
  tv: LucideTv,
  umbrella: LucideUmbrella,
  user: LucideUser,
  users: LucideUsers,
  "utensils-crossed": LucideUtensilsCrossed,
  video: LucideVideo,
  "volume-2": LucideVolume2,
  wallet: LucideWallet,
  watch: LucideWatch,
  wifi: LucideWifi,
  wind: LucideWind,
  wrench: LucideWrench,
  zap: LucideZap,
} as const;

export type IconName = keyof typeof ICON_MAP;

export function getIconComponent(name: string): React.ComponentType<{ className?: string }> {
  const normalizedName = name.toLowerCase().replace(/\s+/g, "-").replace(/_/g, "-");
  return ICON_MAP[normalizedName as IconName] || LucideStar;
}
