// Admin Create Booking - Manual booking without payment gateway
// Status defaults to pending_payment with payment_status=pending
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const log = (level: string, message: string, data?: Record<string, unknown>) => {
  console.log(JSON.stringify({ timestamp: new Date().toISOString(), level, function: "admin-create-booking", message, ...data }));
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const requestId = crypto.randomUUID();

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

    // Verify admin caller via JWT
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userClient = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData, error: userError } = await userClient.auth.getUser();
    if (userError || !userData?.user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check admin role
    const { data: roleCheck } = await supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", userData.user.id)
      .in("role", ["admin", "super_admin", "booking_manager"]);
    if (!roleCheck || roleCheck.length === 0) {
      return new Response(JSON.stringify({ error: "Admin access required" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const {
      guest_name, guest_email, guest_phone,
      room_ids, room_numbers,
      check_in, check_out, total_nights, total_price, price_per_night,
      num_guests, special_requests, remark,
      booking_source = "direct", ota_name, other_source,
      payment_status = "pending", // 'pending' | 'paid'
      user_id,
    } = body;

    if (!guest_name || !guest_email || !check_in || !check_out || !total_price || !room_ids?.length) {
      return new Response(JSON.stringify({ error: "Missing required fields" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get room details
    const { data: rooms, error: roomError } = await supabase
      .from("rooms").select("id, name").in("id", room_ids);
    if (roomError || !rooms?.length) {
      return new Response(JSON.stringify({ error: "Room not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const roomNames = rooms.map((r) => r.name).join(", ");
    const paymentAmount = Math.round(total_price);
    const isPaid = payment_status === "paid";
    const status = isPaid ? "confirmed" : "pending_payment";

    // Create main booking — booking_code auto-generated by trigger
    const { data: booking, error: bookingError } = await supabase
      .from("bookings")
      .insert({
        guest_name,
        guest_email,
        guest_email_backup: guest_email,
        guest_phone: guest_phone || null,
        room_id: room_ids[0],
        check_in,
        check_out,
        total_nights,
        total_price: paymentAmount,
        num_guests: num_guests || 1,
        special_requests: special_requests || null,
        remark: remark || null,
        status,
        payment_status: isPaid ? "paid" : "pending",
        booking_source,
        ota_name: booking_source === "ota" ? ota_name : null,
        other_source: booking_source === "other" ? other_source : null,
        user_id: user_id || null,
        is_inline_payment: false,
        allocated_room_number: room_numbers?.[0] || null,
      })
      .select()
      .single();

    if (bookingError) {
      log("error", "Failed to insert booking", { requestId, error: bookingError });
      return new Response(JSON.stringify({ error: "Failed to create booking", detail: bookingError.message }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Multi-room junction
    if (room_ids.length > 1 || room_numbers?.length) {
      const bookingRooms = room_ids.map((rid: string, idx: number) => ({
        booking_id: booking.id,
        room_id: rid,
        room_number: room_numbers?.[idx] || "",
        price_per_night: Math.round(price_per_night || paymentAmount / total_nights / room_ids.length),
      }));
      const { error: brError } = await supabase.from("booking_rooms").insert(bookingRooms);
      if (brError) log("warn", "booking_rooms insert failed", { requestId, error: brError.message });
    }

    log("info", "Manual booking created", { requestId, bookingId: booking.id, code: booking.booking_code });

    return new Response(JSON.stringify({
      success: true,
      booking: {
        id: booking.id,
        booking_code: booking.booking_code,
        status: booking.status,
        payment_status: booking.payment_status,
        total_price: paymentAmount,
        guest_name,
        guest_email,
        room_name: roomNames,
        check_in,
        check_out,
        total_nights,
      },
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error: unknown) {
    log("error", "Unhandled error", { requestId, error: (error as Error).message });
    return new Response(JSON.stringify({ error: "Internal server error", detail: (error as Error).message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
